/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package nciapp;

import java.io.*;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author x12488942
 */
public class GUIContact extends javax.swing.JFrame {
    private ArrayList <contactArray> cList;
    private String email, type, message;
    private int count, counter;
    File f = new File("email.txt");

    /**
     * Creates new form GUIContact
     */
    public GUIContact() {
        initComponents();
        cList = new ArrayList <>();
        email = new String();
        type = new String();
        message = new String();
        counter = 0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        heading = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        NumberLabel = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        typeLabel = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        numberField = new javax.swing.JTextField();
        emailField = new javax.swing.JTextField();
        studentEmail = new javax.swing.JTextField();
        backwardButton = new javax.swing.JButton();
        homeButton = new javax.swing.JButton();
        title = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        emailContent = new javax.swing.JTextArea();
        submit = new javax.swing.JButton();
        add = new javax.swing.JButton();
        preview = new javax.swing.JButton();
        typeBox = new javax.swing.JComboBox();
        studentEmailLabel = new javax.swing.JLabel();
        menubar = new javax.swing.JLabel();
        wallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(374, 535));
        setPreferredSize(new java.awt.Dimension(374, 535));
        getContentPane().setLayout(null);

        heading.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        heading.setForeground(new java.awt.Color(255, 255, 255));
        heading.setText("Contact Info");
        getContentPane().add(heading);
        heading.setBounds(90, 0, 200, 44);

        nameLabel.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        nameLabel.setForeground(new java.awt.Color(255, 255, 255));
        nameLabel.setText("Name:");
        getContentPane().add(nameLabel);
        nameLabel.setBounds(10, 90, 50, 17);

        NumberLabel.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        NumberLabel.setForeground(new java.awt.Color(255, 255, 255));
        NumberLabel.setText("Number:");
        getContentPane().add(NumberLabel);
        NumberLabel.setBounds(10, 150, 60, 17);

        emailLabel.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        emailLabel.setForeground(new java.awt.Color(255, 255, 255));
        emailLabel.setText("Email:");
        getContentPane().add(emailLabel);
        emailLabel.setBounds(10, 220, 40, 17);

        typeLabel.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        typeLabel.setForeground(new java.awt.Color(255, 255, 255));
        typeLabel.setText("Type:");
        getContentPane().add(typeLabel);
        typeLabel.setBounds(10, 320, 40, 17);

        nameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameFieldActionPerformed(evt);
            }
        });
        getContentPane().add(nameField);
        nameField.setBounds(80, 90, 250, 30);
        nameField.setEditable(false);

        numberField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberFieldActionPerformed(evt);
            }
        });
        getContentPane().add(numberField);
        numberField.setBounds(80, 150, 250, 30);
        numberField.setEditable(false);

        emailField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailFieldActionPerformed(evt);
            }
        });
        getContentPane().add(emailField);
        emailField.setBounds(80, 210, 250, 30);
        emailField.setEditable(false);

        studentEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentEmailActionPerformed(evt);
            }
        });
        getContentPane().add(studentEmail);
        studentEmail.setBounds(90, 280, 160, 30);

        backwardButton.setContentAreaFilled(false);
        backwardButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backwardButtonActionPerformed(evt);
            }
        });
        getContentPane().add(backwardButton);
        backwardButton.setBounds(0, 450, 50, 50);

        homeButton.setContentAreaFilled(false);
        homeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeButtonActionPerformed(evt);
            }
        });
        getContentPane().add(homeButton);
        homeButton.setBounds(150, 450, 60, 50);

        title.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        title.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(title);
        title.setBounds(120, 40, 150, 30);

        emailContent.setColumns(20);
        emailContent.setRows(5);
        jScrollPane1.setViewportView(emailContent);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(90, 350, 200, 60);

        submit.setText("Submit");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });
        getContentPane().add(submit);
        submit.setBounds(140, 420, 80, 23);

        add.setText("Add");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        getContentPane().add(add);
        add.setBounds(50, 420, 51, 23);

        preview.setText("Preview");
        preview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previewActionPerformed(evt);
            }
        });
        getContentPane().add(preview);
        preview.setBounds(250, 420, 73, 23);

        typeBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Inquiry", "Contact Req." }));
        getContentPane().add(typeBox);
        typeBox.setBounds(90, 320, 70, 20);

        studentEmailLabel.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        studentEmailLabel.setForeground(new java.awt.Color(255, 255, 255));
        studentEmailLabel.setText("Your Email:");
        getContentPane().add(studentEmailLabel);
        studentEmailLabel.setBounds(10, 280, 70, 30);

        menubar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nciapp/menuBar.png"))); // NOI18N
        getContentPane().add(menubar);
        menubar.setBounds(0, 450, 360, 50);

        wallpaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nciapp/wallpaper3.png"))); // NOI18N
        wallpaper.setText("jLabel1");
        getContentPane().add(wallpaper);
        wallpaper.setBounds(0, 0, 360, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void setCount(int count) {
        this.count = count;
    }
    private void backwardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backwardButtonActionPerformed
        //Switch block for handling which section to go back to
        switch (count) {
            case 1:
                GUIDisabilitySupport myDisability = new GUIDisabilitySupport();
                myDisability.setVisible(true);
                this.setVisible(false);
                break;
            case 2:
                GUIMathSupport myMath = new GUIMathSupport();
                myMath.setVisible(true);
                this.setVisible(false);
                break;
            case 3:
                GUILearningDevelopment myLearning = new GUILearningDevelopment();
                myLearning.setVisible(true);
                this.setVisible(false);
                break;
            case 4:
                GUIComputingSupport myComputing = new GUIComputingSupport();
                myComputing.setVisible(true);
                this.setVisible(false);
                break;
        }
    }//GEN-LAST:event_backwardButtonActionPerformed
    public void setFields() {
        //Swtich block for setting the information from inheritance files
        switch (count) {
            case 1:
                if (f.exists()) {
                    try {
                        FileInputStream fstream = new FileInputStream("email.txt");
                        DataInputStream in = new DataInputStream(fstream);
                        BufferedReader br = new BufferedReader(new InputStreamReader(in));
                        String str;
                        while ((str = br.readLine()) != null) {
                            studentEmail.setText(str);
                        }
                        in.close();
                    } catch (Exception e) {
                        System.err.println(e);
                    }
                } else {
                    System.out.println("ERROR!");
                }
                DisabilityCon d = new DisabilityCon();
                title.setText("Disability Support");
                nameField.setText(d.getName());
                numberField.setText(d.getNumber());
                emailField.setText(d.getEmail());

                break;
            case 2:
                if (f.exists()) {
                    try {
                        FileInputStream fstream = new FileInputStream("email.txt");
                        DataInputStream in = new DataInputStream(fstream);
                        BufferedReader br = new BufferedReader(new InputStreamReader(in));
                        String str;
                        while ((str = br.readLine()) != null) {
                            studentEmail.setText(str);
                        }
                        in.close();
                    } catch (Exception e) {
                        System.err.println(e);
                    }
                } else {
                    System.out.println("ERROR!");
                }
                MathCon m = new MathCon();
                title.setText("Maths Support");
                nameField.setText(m.getName());
                numberField.setText(m.getNumber());
                emailField.setText(m.getEmail());

                break;
            case 3:
                if (f.exists()) {
                    try {
                        FileInputStream fstream = new FileInputStream("email.txt");
                        DataInputStream in = new DataInputStream(fstream);
                        BufferedReader br = new BufferedReader(new InputStreamReader(in));
                        String str;
                        while ((str = br.readLine()) != null) {
                            studentEmail.setText(str);
                        }
                        in.close();
                    } catch (Exception e) {
                        System.err.println(e);
                    }
                } else {
                    System.out.println("ERROR!");
                }
                LearningCon l = new LearningCon();
                title.setText("Learning Support");
                nameField.setText(l.getName());
                numberField.setText(l.getNumber());
                emailField.setText(l.getEmail());

                break;
            case 4:
                if (f.exists()) {
                    try {
                        FileInputStream fstream = new FileInputStream("email.txt");
                        DataInputStream in = new DataInputStream(fstream);
                        BufferedReader br = new BufferedReader(new InputStreamReader(in));
                        String str;
                        while ((str = br.readLine()) != null) {
                            studentEmail.setText(str);
                        }
                        in.close();
                    } catch (Exception e) {
                        System.err.println(e);
                    }
                } else {
                    System.out.println("ERROR!");
                }
                ComputingCon c = new ComputingCon();
                title.setText("Computing Support");
                nameField.setText(c.getName());
                numberField.setText(c.getNumber());
                emailField.setText(c.getEmail());

                break;
        }
    }
    private void homeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeButtonActionPerformed
        // TODO add your handling code here:
        GUIMainMenu myMainMenu = new GUIMainMenu();
        myMainMenu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_homeButtonActionPerformed

    private void nameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameFieldActionPerformed

    private void emailFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailFieldActionPerformed

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        //Checks if the email was entered
        if (studentEmail.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Please enter you email");
        //Checks if the message was entered     
        } else if (emailContent.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Please write your message");
        //If the email file exists submits the email    
        } else if (f.exists()) {
            JOptionPane.showMessageDialog(null, "Email Sent!");
        //If there was no email file saved, creates a new based on the email entered     
        } else {
            FileWriter writer = null;
            try {
                writer = new FileWriter("email.txt");
                writer.write(studentEmail.getText());
                writer.flush();
                writer.close();
                JOptionPane.showMessageDialog(null, "Email Sent!");
            } catch (IOException ex) {
                Logger.getLogger(GUIContact.class.getName()).log(Level.SEVERE, null, ex);
            } finally {
                try {
                    writer.close();
                } catch (IOException ex) {
                    Logger.getLogger(GUIContact.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_submitActionPerformed

    private void studentEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_studentEmailActionPerformed

    private void numberFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numberFieldActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        //Adds the current text fields in to the array
        email = studentEmail.getText();
        type = (String) typeBox.getSelectedItem();
        message = emailContent.getText();
        
        contactArray c = new contactArray();
        
        c.setEmail(email);
        c.setMessage(message);
        c.setType(type);
        
        cList.add(c);
        
        counter++;
    }//GEN-LAST:event_addActionPerformed

    private void previewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previewActionPerformed
       //Displays all items in the arrayContact
        for(int i = 0; i < cList.size(); i++){
           JOptionPane.showMessageDialog(null, "Your Email: " +cList.get(i).getEmail()+"\n Email Type:  "+cList.get(i).getType()+"\n Your Message: "+cList.get(i).getMessage());
       }
    }//GEN-LAST:event_previewActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIContact.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIContact.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIContact.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIContact.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIContact().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel NumberLabel;
    private javax.swing.JButton add;
    private javax.swing.JButton backwardButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextArea emailContent;
    private javax.swing.JTextField emailField;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JLabel heading;
    private javax.swing.JButton homeButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel menubar;
    private javax.swing.JTextField nameField;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField numberField;
    private javax.swing.JButton preview;
    private javax.swing.JTextField studentEmail;
    private javax.swing.JLabel studentEmailLabel;
    private javax.swing.JButton submit;
    private javax.swing.JLabel title;
    private javax.swing.JComboBox typeBox;
    private javax.swing.JLabel typeLabel;
    private javax.swing.JLabel wallpaper;
    // End of variables declaration//GEN-END:variables
}
