/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package nciapp;

import java.awt.Desktop;

/**
 *
 * @author x12488942
 */
public class GUIDisabilitySupport extends javax.swing.JFrame {

    /**
     * Creates new form DisabilitySupportGUI
     */
    public GUIDisabilitySupport() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        infoLabel = new javax.swing.JLabel();
        mapButton = new javax.swing.JButton();
        contactButton = new javax.swing.JButton();
        infoButton = new javax.swing.JButton();
        learningSupportButton = new javax.swing.JButton();
        homeButton = new javax.swing.JButton();
        forwardButton = new javax.swing.JButton();
        backwardButton = new javax.swing.JButton();
        heading = new javax.swing.JLabel();
        wheelChair = new javax.swing.JLabel();
        menuBar = new javax.swing.JLabel();
        wallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(374, 535));
        getContentPane().setLayout(null);

        infoLabel.setBackground(new java.awt.Color(255, 255, 255));
        infoLabel.setText("<html> National College of Ireland is committed to providing equal access to education  and equal opportunities for students  with disabilities.  \nThe College encourages students to be open about their disability and to discuss their individual needs with the Disability Officer. <br/> \nIt is very important that students disclose a disability early in the academic year to ensure that necessary supports are provided. \nBy delaying disclosure of a disability, students may be missing out on essential supports which can help with everything from participation in lectures right through to sitting exams.\n<br/><br/> CLICK TO CLOSE </html>");
        infoLabel.setOpaque(true);
        infoLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                infoLabelMouseClicked(evt);
            }
        });
        getContentPane().add(infoLabel);
        infoLabel.setBounds(50, 80, 260, 250);
        infoLabel.setVisible(false);

        mapButton.setText("Map");
        mapButton.setPreferredSize(new java.awt.Dimension(70, 24));
        mapButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mapButtonActionPerformed(evt);
            }
        });
        getContentPane().add(mapButton);
        mapButton.setBounds(60, 200, 80, 60);

        contactButton.setText("Contact");
        contactButton.setPreferredSize(new java.awt.Dimension(70, 24));
        contactButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactButtonActionPerformed(evt);
            }
        });
        getContentPane().add(contactButton);
        contactButton.setBounds(60, 320, 80, 60);

        infoButton.setText("Info");
        infoButton.setPreferredSize(new java.awt.Dimension(70, 24));
        infoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                infoButtonActionPerformed(evt);
            }
        });
        getContentPane().add(infoButton);
        infoButton.setBounds(220, 200, 80, 60);

        learningSupportButton.setText("<html>\nLearning\n<br/>\nSupport\n</html>");
        learningSupportButton.setPreferredSize(new java.awt.Dimension(70, 24));
        learningSupportButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                learningSupportButtonActionPerformed(evt);
            }
        });
        getContentPane().add(learningSupportButton);
        learningSupportButton.setBounds(220, 320, 80, 60);

        homeButton.setContentAreaFilled(false);
        homeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeButtonActionPerformed(evt);
            }
        });
        getContentPane().add(homeButton);
        homeButton.setBounds(160, 450, 40, 50);

        forwardButton.setContentAreaFilled(false);
        getContentPane().add(forwardButton);
        forwardButton.setBounds(313, 450, 50, 50);

        backwardButton.setContentAreaFilled(false);
        getContentPane().add(backwardButton);
        backwardButton.setBounds(0, 450, 40, 50);

        heading.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        heading.setForeground(new java.awt.Color(255, 255, 255));
        heading.setText("Disability Support");
        getContentPane().add(heading);
        heading.setBounds(60, 0, 290, 110);

        wheelChair.setBackground(new java.awt.Color(0, 0, 0));
        wheelChair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nciapp/1242796267486489866Handicapped_Accessible_sign.svg.med.png"))); // NOI18N
        getContentPane().add(wheelChair);
        wheelChair.setBounds(30, 140, 300, 300);

        menuBar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nciapp/menuBar.png"))); // NOI18N
        menuBar.setText("jLabel1");
        menuBar.setPreferredSize(new java.awt.Dimension(360, 50));
        getContentPane().add(menuBar);
        menuBar.setBounds(0, 450, 360, 50);

        wallpaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nciapp/wallpaper3.png"))); // NOI18N
        getContentPane().add(wallpaper);
        wallpaper.setBounds(0, 0, 360, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void learningSupportButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_learningSupportButtonActionPerformed
        GUILearningSupport mySupport = new GUILearningSupport();
        mySupport.setVisible(true);
        mySupport.setLocationRelativeTo(this);
        this.setVisible(false);

    }//GEN-LAST:event_learningSupportButtonActionPerformed

    private void contactButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactButtonActionPerformed
        GUIContact myContact = new GUIContact();
        int count = 1;
        myContact.setCount(count);
        myContact.setFields();
        myContact.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_contactButtonActionPerformed

    private void infoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_infoButtonActionPerformed
        infoLabel.setVisible(true);
    }//GEN-LAST:event_infoButtonActionPerformed

    private void mapButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mapButtonActionPerformed
        try {
         //Sets url string for display and opens up a browser
         String url = "http://www.ncirl.ie/About_NCI/Contact_Details/Location_Map";
         java.awt.Desktop.getDesktop().browse(java.net.URI.create(url));
       }
       catch (java.io.IOException e) {
           System.out.println(e.getMessage());
       }
    }//GEN-LAST:event_mapButtonActionPerformed

    private void infoLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_infoLabelMouseClicked
        infoLabel.setVisible(false);
    }//GEN-LAST:event_infoLabelMouseClicked

    private void homeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeButtonActionPerformed
        GUIMainMenu myMenu = new GUIMainMenu();
        myMenu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_homeButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIDisabilitySupport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIDisabilitySupport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIDisabilitySupport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIDisabilitySupport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new GUIDisabilitySupport().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backwardButton;
    private javax.swing.JButton contactButton;
    private javax.swing.JButton forwardButton;
    private javax.swing.JLabel heading;
    private javax.swing.JButton homeButton;
    private javax.swing.JButton infoButton;
    private javax.swing.JLabel infoLabel;
    private javax.swing.JButton learningSupportButton;
    private javax.swing.JButton mapButton;
    private javax.swing.JLabel menuBar;
    private javax.swing.JLabel wallpaper;
    private javax.swing.JLabel wheelChair;
    // End of variables declaration//GEN-END:variables
}
