
package nciapp;

import javax.swing.JOptionPane;
/**
 * NCI App
 * Sean Keeley
 * Maths Support Section
 */
public class GUIEvents extends javax.swing.JFrame {

    /**
     * Creates new form Events
     */
    public GUIEvents() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backButton = new javax.swing.JButton();
        homeButton = new javax.swing.JButton();
        forwardButton = new javax.swing.JButton();
        Calender = new javax.swing.JButton();
        Workshops = new javax.swing.JButton();
        calenderLabel = new javax.swing.JLabel();
        titleText = new javax.swing.JLabel();
        menuBar = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(374, 535));
        getContentPane().setLayout(null);

        backButton.setContentAreaFilled(false);
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        getContentPane().add(backButton);
        backButton.setBounds(0, 450, 60, 50);

        homeButton.setContentAreaFilled(false);
        homeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeButtonActionPerformed(evt);
            }
        });
        getContentPane().add(homeButton);
        homeButton.setBounds(150, 450, 60, 50);

        forwardButton.setContentAreaFilled(false);
        getContentPane().add(forwardButton);
        forwardButton.setBounds(310, 450, 50, 50);

        Calender.setText("Calender");
        Calender.setOpaque(false);
        Calender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalenderActionPerformed(evt);
            }
        });
        getContentPane().add(Calender);
        Calender.setBounds(40, 250, 100, 70);

        Workshops.setText("Workshops");
        Workshops.setOpaque(false);
        Workshops.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WorkshopsActionPerformed(evt);
            }
        });
        getContentPane().add(Workshops);
        Workshops.setBounds(40, 150, 100, 70);

        calenderLabel.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        calenderLabel.setForeground(new java.awt.Color(240, 240, 240));
        calenderLabel.setText("<html> The exams this semester start on the 2nd of May and run until the 18th. The support centre will run exam focused sessions at somestage before this date. Check back for details soon. <br><br>\nThere will be focused revision sessions for each subject held before the exams in order to give the student the best possible start to his/her exams. \n</html>");
        calenderLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                calenderLabelMouseClicked(evt);
            }
        });
        getContentPane().add(calenderLabel);
        calenderLabel.setBounds(170, 80, 170, 340);
        calenderLabel.setVisible(false);

        titleText.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        titleText.setForeground(new java.awt.Color(240, 240, 240));
        titleText.setText("Events");
        getContentPane().add(titleText);
        titleText.setBounds(270, 10, 130, 40);

        menuBar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nciapp/menuBar.png"))); // NOI18N
        getContentPane().add(menuBar);
        menuBar.setBounds(0, 450, 360, 50);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nciapp/wallpaper3.png"))); // NOI18N
        background.setPreferredSize(new java.awt.Dimension(374, 535));
        getContentPane().add(background);
        background.setBounds(0, -40, 374, 570);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        GUIMathSupport myMaths = new GUIMathSupport();
        myMaths.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_backButtonActionPerformed

    private void homeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeButtonActionPerformed
        // TODO add your handling code here:
         //link to home page
        //Maths myMaths = new Maths();
       // myMaths.setVisible(true);
    }//GEN-LAST:event_homeButtonActionPerformed
    //try catch method to link to a workshops section on NCIRL.ie
    private void WorkshopsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WorkshopsActionPerformed
        // TODO add your handling code here:
        try {
        String URL ="http://tinyurl.com/mathsworkshops";
        java.awt.Desktop.getDesktop().browse(java.net.URI.create(URL));
    }                                            
            catch (Exception e) {
                JOptionPane.showMessageDialog(null,e.getMessage());
            }
    
    }//GEN-LAST:event_WorkshopsActionPerformed

    private void CalenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalenderActionPerformed
        // TODO add your handling code here:
       calenderLabel.setVisible(true);
    }//GEN-LAST:event_CalenderActionPerformed

    private void calenderLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_calenderLabelMouseClicked
        // TODO add your handling code here:
        calenderLabel.setVisible(false);
    }//GEN-LAST:event_calenderLabelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIEvents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIEvents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIEvents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIEvents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new GUIEvents().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Calender;
    private javax.swing.JButton Workshops;
    private javax.swing.JButton backButton;
    private javax.swing.JLabel background;
    private javax.swing.JLabel calenderLabel;
    private javax.swing.JButton forwardButton;
    private javax.swing.JButton homeButton;
    private javax.swing.JLabel menuBar;
    private javax.swing.JLabel titleText;
    // End of variables declaration//GEN-END:variables
}
