package nciapp;




import java.awt.Desktop;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileWriter;
import java.io.IOException;
import java.io.InputStream;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import sun.audio.AudioPlayer;
import sun.audio.AudioStream;
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Robbie
 */
public class GUILearningDevelopment extends javax.swing.JFrame {

    /**
     * Creates new form HomeJFrame
     * 
     
     */
    boolean flag;
    //File f = new File("A1.wav");
    
    private ArrayList<Learning>aList;
    private String subject, name, studentnum;
    private int count;
    
    
    
    
    public GUILearningDevelopment() {
        initComponents();
        aList = new ArrayList<>();
        subject = new String();
        name = new String();
        studentnum = new String();
        count = 0;
        
        //Stopbtn.setVisible(false);
        manualB.setVisible(false);
        harvardB.setVisible(false);
        contact.setVisible(false);
        extraclass.setVisible(false);
        Manual.setVisible(false);
        Harvard.setVisible(false);
        ExtraClasses.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        ExtraClasses = new javax.swing.JPanel();
        ECHeading = new javax.swing.JLabel();
        Subject = new javax.swing.JLabel();
        Lecturer = new javax.swing.JLabel();
        Num = new javax.swing.JLabel();
        Submit = new javax.swing.JButton();
        Requested = new javax.swing.JButton();
        Clear = new javax.swing.JButton();
        SubjectTF = new javax.swing.JTextField();
        StudentNumTF = new javax.swing.JTextField();
        LecturerTF = new javax.swing.JTextField();
        Manual = new javax.swing.JPanel();
        Mheading = new javax.swing.JLabel();
        Mtext = new javax.swing.JLabel();
        pdfbtn = new javax.swing.JButton();
        varkbtn = new javax.swing.JButton();
        Harvard = new javax.swing.JPanel();
        Heading = new javax.swing.JLabel();
        Playbtn = new javax.swing.JButton();
        text = new javax.swing.JLabel();
        Welcom = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        manualB = new javax.swing.JButton();
        harvardB = new javax.swing.JButton();
        contact = new javax.swing.JButton();
        extraclass = new javax.swing.JButton();
        enterDevelopment = new javax.swing.JButton();
        homeButton = new javax.swing.JButton();
        BackButton = new javax.swing.JButton();
        menubar = new javax.swing.JLabel();
        heading = new javax.swing.JLabel();
        wallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFocusCycleRoot(false);
        setMinimumSize(new java.awt.Dimension(374, 535));
        getContentPane().setLayout(null);

        ExtraClasses.setOpaque(false);

        ECHeading.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ECHeading.setForeground(new java.awt.Color(255, 255, 255));
        ECHeading.setText("Extra Classes Form");

        Subject.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Subject.setForeground(new java.awt.Color(255, 255, 255));
        Subject.setText("Subject");

        Lecturer.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Lecturer.setForeground(new java.awt.Color(255, 255, 255));
        Lecturer.setText("Lecturer");

        Num.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Num.setForeground(new java.awt.Color(255, 255, 255));
        Num.setText("Student Num.");

        Submit.setText("Submit");
        Submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitActionPerformed(evt);
            }
        });

        Requested.setText("Requested");
        Requested.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RequestedActionPerformed(evt);
            }
        });

        Clear.setText("Clear");
        Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ExtraClassesLayout = new javax.swing.GroupLayout(ExtraClasses);
        ExtraClasses.setLayout(ExtraClassesLayout);
        ExtraClassesLayout.setHorizontalGroup(
            ExtraClassesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ExtraClassesLayout.createSequentialGroup()
                .addGroup(ExtraClassesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ExtraClassesLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(ExtraClassesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ECHeading, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(ExtraClassesLayout.createSequentialGroup()
                                .addGroup(ExtraClassesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Subject)
                                    .addComponent(Lecturer)
                                    .addComponent(Num))
                                .addGap(33, 33, 33)
                                .addGroup(ExtraClassesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LecturerTF, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(SubjectTF, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(StudentNumTF, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(ExtraClassesLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(Submit, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Requested, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ExtraClassesLayout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(Clear, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        ExtraClassesLayout.setVerticalGroup(
            ExtraClassesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ExtraClassesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ExtraClassesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(ExtraClassesLayout.createSequentialGroup()
                        .addComponent(ECHeading, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(ExtraClassesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Subject)
                            .addComponent(SubjectTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(52, 52, 52)
                        .addGroup(ExtraClassesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LecturerTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Lecturer))
                        .addGap(44, 44, 44)
                        .addComponent(StudentNumTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Num))
                .addGap(18, 18, 18)
                .addGroup(ExtraClassesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Submit)
                    .addComponent(Requested))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Clear)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        ExtraClasses.setBounds(0, 0, 260, 340);
        jLayeredPane1.add(ExtraClasses, javax.swing.JLayeredPane.DEFAULT_LAYER);

        Manual.setMaximumSize(new java.awt.Dimension(260, 380));
        Manual.setOpaque(false);
        Manual.setPreferredSize(new java.awt.Dimension(260, 380));

        Mheading.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Mheading.setForeground(new java.awt.Color(255, 255, 255));
        Mheading.setText("Development Manual");

        Mtext.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Mtext.setForeground(new java.awt.Color(255, 255, 255));
        Mtext.setText("<html><p>The Learning Development Manual can provide you with the tools and advice to become a more effective learner in Higher Education. Covering four units, the manual aims to help each student become aware of their learning style and to adopt an individual learning strategy.</p></html>");

        pdfbtn.setText("ManualPdf");
        pdfbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pdfbtnActionPerformed(evt);
            }
        });

        varkbtn.setText("Vark Test");
        varkbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                varkbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ManualLayout = new javax.swing.GroupLayout(Manual);
        Manual.setLayout(ManualLayout);
        ManualLayout.setHorizontalGroup(
            ManualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ManualLayout.createSequentialGroup()
                .addGroup(ManualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ManualLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Mheading, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ManualLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(ManualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Mtext, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(ManualLayout.createSequentialGroup()
                                .addComponent(varkbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(pdfbtn)))))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        ManualLayout.setVerticalGroup(
            ManualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ManualLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Mheading, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(Mtext, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addGroup(ManualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pdfbtn)
                    .addComponent(varkbtn))
                .addContainerGap(82, Short.MAX_VALUE))
        );

        Manual.setBounds(0, 0, 260, 380);
        jLayeredPane1.add(Manual, javax.swing.JLayeredPane.DRAG_LAYER);

        Harvard.setOpaque(false);
        Harvard.setLayout(null);

        Heading.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Heading.setForeground(new java.awt.Color(255, 255, 255));
        Heading.setText("Harvard Style");
        Harvard.add(Heading);
        Heading.setBounds(10, 11, 120, 35);

        Playbtn.setText("Play Audio");
        Playbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlaybtnActionPerformed(evt);
            }
        });
        Harvard.add(Playbtn);
        Playbtn.setBounds(60, 260, 130, 23);

        text.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        text.setForeground(new java.awt.Color(255, 255, 255));
        text.setText("<html><p>When producing a piece of written work you need to acknowledge the words and ideas of others that you use, by citing and referencing them. There are several referencing systems in existence however this is the one most used here at NCI.</p></html>");
        Harvard.add(text);
        text.setBounds(20, 57, 204, 225);

        Harvard.setBounds(0, 0, 260, 320);
        jLayeredPane1.add(Harvard, javax.swing.JLayeredPane.DEFAULT_LAYER);

        Welcom.setOpaque(false);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("<html>\n<p>The Learning Support Service is centred around some core areas such as academic writing, reading, researching, studying, note-taking, exam revision and in general, a focus on aiding a student in all manners of academic advancement.For more information on the specific features of the service itself, enter this section below.</p>\n</html>\n\n");

        javax.swing.GroupLayout WelcomLayout = new javax.swing.GroupLayout(Welcom);
        Welcom.setLayout(WelcomLayout);
        WelcomLayout.setHorizontalGroup(
            WelcomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, WelcomLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        WelcomLayout.setVerticalGroup(
            WelcomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WelcomLayout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        Welcom.setBounds(0, 10, 260, 320);
        jLayeredPane1.add(Welcom, javax.swing.JLayeredPane.DEFAULT_LAYER);

        manualB.setText("Manual");
        manualB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manualBActionPerformed(evt);
            }
        });
        manualB.setBounds(10, 40, 110, 110);
        jLayeredPane1.add(manualB, javax.swing.JLayeredPane.DEFAULT_LAYER);

        harvardB.setText("Harverd Style");
        harvardB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                harvardBActionPerformed(evt);
            }
        });
        harvardB.setBounds(140, 40, 110, 110);
        jLayeredPane1.add(harvardB, javax.swing.JLayeredPane.DEFAULT_LAYER);

        contact.setText("Contact");
        contact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactActionPerformed(evt);
            }
        });
        contact.setBounds(10, 190, 110, 100);
        jLayeredPane1.add(contact, javax.swing.JLayeredPane.DEFAULT_LAYER);

        extraclass.setText("Extra Class");
        extraclass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                extraclassActionPerformed(evt);
            }
        });
        extraclass.setBounds(140, 190, 110, 100);
        jLayeredPane1.add(extraclass, javax.swing.JLayeredPane.DEFAULT_LAYER);

        getContentPane().add(jLayeredPane1);
        jLayeredPane1.setBounds(55, 80, 260, 340);

        enterDevelopment.setText("Enter Development");
        enterDevelopment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterDevelopmentActionPerformed(evt);
            }
        });
        getContentPane().add(enterDevelopment);
        enterDevelopment.setBounds(60, 420, 250, 23);

        homeButton.setContentAreaFilled(false);
        homeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeButtonActionPerformed(evt);
            }
        });
        getContentPane().add(homeButton);
        homeButton.setBounds(150, 450, 60, 50);

        BackButton.setContentAreaFilled(false);
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });
        getContentPane().add(BackButton);
        BackButton.setBounds(0, 450, 50, 50);

        menubar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nciapp/menuBar.png"))); // NOI18N
        menubar.setText("jLabel4");
        getContentPane().add(menubar);
        menubar.setBounds(0, 450, 360, 50);

        heading.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        heading.setForeground(new java.awt.Color(255, 255, 255));
        heading.setText("Learning Development");
        getContentPane().add(heading);
        heading.setBounds(10, 10, 350, 50);

        wallpaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nciapp/wallpaper3.png"))); // NOI18N
        wallpaper.setMinimumSize(new java.awt.Dimension(364, 500));
        wallpaper.setPreferredSize(new java.awt.Dimension(364, 500));
        getContentPane().add(wallpaper);
        wallpaper.setBounds(0, 0, 370, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void enterDevelopmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterDevelopmentActionPerformed
        heading.setVisible(true);
        manualB.setVisible(true);
        harvardB.setVisible(true);
        contact.setVisible(true);
        extraclass.setVisible(true);
        enterDevelopment.setVisible(false);
        Welcom.setVisible(false);
        
        
        
    }//GEN-LAST:event_enterDevelopmentActionPerformed
public void showButtons(){
       heading.setVisible(true);
        manualB.setVisible(true);
        harvardB.setVisible(true);
        contact.setVisible(true);
       extraclass.setVisible(true);
        enterDevelopment.setVisible(false);
        Welcom.setVisible(false);
}
    private void manualBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manualBActionPerformed
        manualB.setVisible(false);
        harvardB.setVisible(false);
        contact.setVisible(false);
        extraclass.setVisible(false);
        Manual.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_manualBActionPerformed

    private void harvardBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_harvardBActionPerformed
       Manual.setVisible(false);
       Harvard.setVisible(true);
       manualB.setVisible(false);
       harvardB.setVisible(false);
       contact.setVisible(false);
       extraclass.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_harvardBActionPerformed

    private void extraclassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_extraclassActionPerformed
       ExtraClasses.setVisible(true);
       manualB.setVisible(false);
       harvardB.setVisible(false);
       contact.setVisible(false);
       extraclass.setVisible(false);
       
        // TODO add your handling code here:
    }//GEN-LAST:event_extraclassActionPerformed

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
       heading.setVisible(true);
       manualB.setVisible(true);
       harvardB.setVisible(true);
       contact.setVisible(true);
       extraclass.setVisible(true);
       ExtraClasses.setVisible(false);
       Harvard.setVisible(false);
       Manual.setVisible(false);
       
        // TODO add your handling code here:
    }//GEN-LAST:event_BackButtonActionPerformed

    private void homeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeButtonActionPerformed
        // TODO add your handling code here:
        GUIMainMenu myMainMenu = new GUIMainMenu();
        myMainMenu.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_homeButtonActionPerformed

    private void contactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactActionPerformed
        // TODO add your handling code here:
        GUIContact myContact = new GUIContact();
        int count = 3;
        myContact.setCount(count);
        myContact.setFields();
        myContact.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_contactActionPerformed

    private void SubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitActionPerformed
        try {
            // TODO add your handling code here:
            File outFile;
            FileWriter fw;
            BufferedWriter bw;
            
            
            subject = SubjectTF.getText();
            name = LecturerTF.getText();
            studentnum = StudentNumTF.getText();
            
            Learning l = new Learning();
            
            
            l.setSubject(subject);
            l.setStudentnum(studentnum);
            l.setName(name);
            
            
            
            aList.add(l);
            count ++;
            
            outFile = new File("data.txt");
            fw = new FileWriter(outFile);
            bw = new BufferedWriter(fw);
            
            bw.write(name);
            bw.write(studentnum);
            bw.write(subject);
            bw.close();
        } catch (IOException ex) {
            Logger.getLogger(GUILearningDevelopment.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
    }//GEN-LAST:event_SubmitActionPerformed

    private void RequestedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RequestedActionPerformed
        // TODO add your handling code here:
        for(int i = 0; i< aList.size(); i++){
            JOptionPane.showMessageDialog(null, "subject; "+aList.get(i).getSubject() + "\nLecturer "+aList.get(i).getName() + "\nStudentNum  "+aList.get(i).getStudentnum());
        }
    }//GEN-LAST:event_RequestedActionPerformed

    private void ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearActionPerformed
        // TODO add your handling code here:
        SubjectTF.setText("");
        StudentNumTF.setText("");
        LecturerTF.setText("");
        
    }//GEN-LAST:event_ClearActionPerformed

    private void PlaybtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlaybtnActionPerformed
        // TODO add your handling code here:
        InputStream in;
       
        try {
            in = new FileInputStream(new File("A1.wav"));
            AudioStream audio = new AudioStream(in);
            if (flag == true) {
                AudioPlayer.player.start(audio);
                flag = false;
              //  Stopbtn.setVisible(true);
                Playbtn.setVisible(false);
            } else if(flag ==false ){
                AudioPlayer.player.stop(audio);
                 flag = true;
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "If unable to get file, please visit the website " + "\n for more information");
        }
    }//GEN-LAST:event_PlaybtnActionPerformed

    private void pdfbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pdfbtnActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            File pd = new File("LM.pdf");
            Desktop.getDesktop().open(pd);
        } catch (IOException ex) {
            Logger.getLogger(GUILearningDevelopment.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_pdfbtnActionPerformed

    private void varkbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_varkbtnActionPerformed
        try {
            // TODO add your handling code here:
            String URL = "www.vark-learn.com/english/page.asp?p=questionnaire";
            java.awt.Desktop.getDesktop().browse(java.net.URI.create(URL));
        } catch (IOException ex) {
            Logger.getLogger(GUILearningDevelopment.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_varkbtnActionPerformed

    /**
     * @param args the command line arguments
     */
 public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUILearningDevelopment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUILearningDevelopment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUILearningDevelopment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUILearningDevelopment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUILearningDevelopment().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JButton Clear;
    private javax.swing.JLabel ECHeading;
    private javax.swing.JPanel ExtraClasses;
    private javax.swing.JPanel Harvard;
    private javax.swing.JLabel Heading;
    private javax.swing.JLabel Lecturer;
    private javax.swing.JTextField LecturerTF;
    private javax.swing.JPanel Manual;
    private javax.swing.JLabel Mheading;
    private javax.swing.JLabel Mtext;
    private javax.swing.JLabel Num;
    private javax.swing.JButton Playbtn;
    private javax.swing.JButton Requested;
    private javax.swing.JTextField StudentNumTF;
    private javax.swing.JLabel Subject;
    private javax.swing.JTextField SubjectTF;
    private javax.swing.JButton Submit;
    private javax.swing.JPanel Welcom;
    private javax.swing.JButton contact;
    private javax.swing.JButton enterDevelopment;
    private javax.swing.JButton extraclass;
    private javax.swing.JButton harvardB;
    private javax.swing.JLabel heading;
    private javax.swing.JButton homeButton;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JButton manualB;
    private javax.swing.JLabel menubar;
    private javax.swing.JButton pdfbtn;
    private javax.swing.JLabel text;
    private javax.swing.JButton varkbtn;
    private javax.swing.JLabel wallpaper;
    // End of variables declaration//GEN-END:variables
}
