/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package nciapp;

/**
 *
 * @author x12383876
 */
public class GUIMainMenu extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    public GUIMainMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Computing = new javax.swing.JButton();
        Maths = new javax.swing.JButton();
        Learning = new javax.swing.JButton();
        Disability = new javax.swing.JButton();
        Wallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(364, 535));
        setPreferredSize(new java.awt.Dimension(376, 539));
        getContentPane().setLayout(null);

        Computing.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        Computing.setText("Computing");
        Computing.setMargin(new java.awt.Insets(2, 7, 2, 7));
        Computing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComputingActionPerformed(evt);
            }
        });
        getContentPane().add(Computing);
        Computing.setBounds(30, 240, 120, 50);

        Maths.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        Maths.setText("Maths");
        Maths.setMargin(new java.awt.Insets(2, 7, 2, 7));
        Maths.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MathsActionPerformed(evt);
            }
        });
        getContentPane().add(Maths);
        Maths.setBounds(30, 330, 120, 50);

        Learning.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        Learning.setText("Learning");
        Learning.setMargin(new java.awt.Insets(2, 7, 2, 7));
        Learning.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LearningActionPerformed(evt);
            }
        });
        getContentPane().add(Learning);
        Learning.setBounds(200, 240, 120, 50);

        Disability.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        Disability.setText("Disability");
        Disability.setMargin(new java.awt.Insets(2, 7, 2, 7));
        Disability.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisabilityActionPerformed(evt);
            }
        });
        getContentPane().add(Disability);
        Disability.setBounds(200, 330, 120, 50);

        Wallpaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nciapp/wallpaperLogo.png"))); // NOI18N
        Wallpaper.setText("jLabel1");
        Wallpaper.setPreferredSize(new java.awt.Dimension(376, 539));
        getContentPane().add(Wallpaper);
        Wallpaper.setBounds(0, 0, 360, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ComputingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComputingActionPerformed
        // TODO add your handling code here:
        GUIComputingSupport myComputing = new GUIComputingSupport();
        myComputing.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_ComputingActionPerformed

    private void DisabilityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisabilityActionPerformed
        // TODO add your handling code here:
        GUIDisabilitySupport myDisability = new GUIDisabilitySupport();
        myDisability.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_DisabilityActionPerformed

    private void LearningActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LearningActionPerformed
        // TODO add your handling code here:
        GUILearningDevelopment myDevelopment = new GUILearningDevelopment();
        myDevelopment.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_LearningActionPerformed

    private void MathsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MathsActionPerformed
        // TODO add your handling code here:
        GUIMathSupport myMath = new GUIMathSupport();
        myMath.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_MathsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new GUIMainMenu().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Computing;
    private javax.swing.JButton Disability;
    private javax.swing.JButton Learning;
    private javax.swing.JButton Maths;
    private javax.swing.JLabel Wallpaper;
    // End of variables declaration//GEN-END:variables
}
