/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package nciapp;

/**
 *
 * @author x12383876
 */
public class GUIOneOnOneSupport extends javax.swing.JFrame {

    /**
     * Creates new form Computing
     */
    public GUIOneOnOneSupport() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        OneOnOneSupport = new javax.swing.JLabel();
        Body = new javax.swing.JLabel();
        AppointmentBtn = new javax.swing.JButton();
        menuRight = new javax.swing.JButton();
        menuMiddle = new javax.swing.JButton();
        menuLeft = new javax.swing.JButton();
        MenuBar = new javax.swing.JLabel();
        Wallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(374, 535));
        setPreferredSize(new java.awt.Dimension(376, 539));
        getContentPane().setLayout(null);

        OneOnOneSupport.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        OneOnOneSupport.setForeground(new java.awt.Color(255, 255, 255));
        OneOnOneSupport.setText("1-On-1 Support");
        getContentPane().add(OneOnOneSupport);
        OneOnOneSupport.setBounds(120, 10, 230, 30);

        Body.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        Body.setForeground(new java.awt.Color(255, 255, 255));
        Body.setText("<html>\n\nYou can organise 1 on 1 support with teachers if you need help.\n<br>\n<br>\nEither talk to them in class or go to the Contact page and get in direct contact with them.\n<br>\n<br>\nYou can use the button below to keep track of your Appointments.\n\n\n</html>\n");
        getContentPane().add(Body);
        Body.setBounds(60, 100, 260, 210);

        AppointmentBtn.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        AppointmentBtn.setText("Appointments");
        AppointmentBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AppointmentBtnActionPerformed(evt);
            }
        });
        getContentPane().add(AppointmentBtn);
        AppointmentBtn.setBounds(110, 320, 140, 60);

        menuRight.setContentAreaFilled(false);
        menuRight.setPreferredSize(new java.awt.Dimension(50, 50));
        menuRight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRightActionPerformed(evt);
            }
        });
        getContentPane().add(menuRight);
        menuRight.setBounds(310, 450, 50, 50);

        menuMiddle.setContentAreaFilled(false);
        menuMiddle.setPreferredSize(new java.awt.Dimension(50, 50));
        menuMiddle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuMiddleActionPerformed(evt);
            }
        });
        getContentPane().add(menuMiddle);
        menuMiddle.setBounds(150, 450, 60, 50);

        menuLeft.setContentAreaFilled(false);
        menuLeft.setPreferredSize(new java.awt.Dimension(50, 50));
        menuLeft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuLeftActionPerformed(evt);
            }
        });
        getContentPane().add(menuLeft);
        menuLeft.setBounds(0, 450, 60, 50);

        MenuBar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nciapp/menuBar2.gif"))); // NOI18N
        MenuBar.setText("jLabel1");
        MenuBar.setToolTipText("");
        MenuBar.setPreferredSize(new java.awt.Dimension(360, 50));
        getContentPane().add(MenuBar);
        MenuBar.setBounds(0, 450, 360, 50);

        Wallpaper.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        Wallpaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nciapp/wallpaper3.png"))); // NOI18N
        Wallpaper.setMaximumSize(new java.awt.Dimension(412, 500));
        getContentPane().add(Wallpaper);
        Wallpaper.setBounds(0, 0, 360, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuLeftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuLeftActionPerformed
        // TODO add your handling code here:
        GUIComputingSupport myComputing = new GUIComputingSupport();
        myComputing.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_menuLeftActionPerformed

    private void menuMiddleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuMiddleActionPerformed
        // TODO add your handling code here:
        GUIMainMenu myMainMenu = new GUIMainMenu();
        myMainMenu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_menuMiddleActionPerformed

    private void AppointmentBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AppointmentBtnActionPerformed
        // TODO add your handling code here:
        ArrayGUI myArrayGUI = new ArrayGUI();
        myArrayGUI.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_AppointmentBtnActionPerformed

    private void menuRightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRightActionPerformed
        // TODO add your handling code here:
        ArrayGUI myArrayGUI = new ArrayGUI();
        myArrayGUI.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_menuRightActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIOneOnOneSupport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIOneOnOneSupport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIOneOnOneSupport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIOneOnOneSupport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new GUIOneOnOneSupport().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AppointmentBtn;
    private javax.swing.JLabel Body;
    private javax.swing.JLabel MenuBar;
    private javax.swing.JLabel OneOnOneSupport;
    private javax.swing.JLabel Wallpaper;
    private javax.swing.JButton menuLeft;
    private javax.swing.JButton menuMiddle;
    private javax.swing.JButton menuRight;
    // End of variables declaration//GEN-END:variables
}
