
package nciapp;

/**
 * NCI App
 * Sean Keeley
 * Maths Support Section
 */
public class GUIQuiz extends javax.swing.JFrame {
//The Quiz is done,but i keep getting it wrong when i try and put it into netbeans
    //It will be done for the final upload. 
    /**
     * Creates new form QuizGUI
     */
    public GUIQuiz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        helpLabel = new javax.swing.JLabel();
        titleText = new javax.swing.JLabel();
        playQuizButton = new javax.swing.JButton();
        pastResultsButton = new javax.swing.JButton();
        helpButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        homeButton = new javax.swing.JButton();
        forwardButton = new javax.swing.JButton();
        menuBar = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(374, 535));
        setPreferredSize(new java.awt.Dimension(374, 535));
        getContentPane().setLayout(null);

        helpLabel.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        helpLabel.setForeground(new java.awt.Color(240, 240, 240));
        helpLabel.setText("<html>The Quiz will ask you random mathamatical questions. <br> <br> <br> The subjects will range from Addition and Subtraction to Multiplication and Division. <br> <br> <br> Read the question, type your answer into the Answer box and press check to confirm your answer <br> <br> <br> A message will appear saying your result.    <br><br><br> If you want to try again, press the 'Clear button' </html>");
        helpLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                helpLabelMouseClicked(evt);
            }
        });
        getContentPane().add(helpLabel);
        helpLabel.setBounds(160, 70, 170, 370);
        helpLabel.setVisible(false);

        titleText.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        titleText.setForeground(new java.awt.Color(255, 255, 255));
        titleText.setText(" Revision Quiz");
        getContentPane().add(titleText);
        titleText.setBounds(210, 0, 150, 70);

        playQuizButton.setText("Play Quiz");
        playQuizButton.setOpaque(false);
        playQuizButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playQuizButtonActionPerformed(evt);
            }
        });
        getContentPane().add(playQuizButton);
        playQuizButton.setBounds(20, 130, 80, 60);

        pastResultsButton.setText("<html>       Previous </br> Results   </html>");
        pastResultsButton.setOpaque(false);
        pastResultsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pastResultsButtonActionPerformed(evt);
            }
        });
        getContentPane().add(pastResultsButton);
        pastResultsButton.setBounds(20, 210, 80, 60);

        helpButton.setText("Help");
        helpButton.setOpaque(false);
        helpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpButtonActionPerformed(evt);
            }
        });
        getContentPane().add(helpButton);
        helpButton.setBounds(20, 300, 80, 60);

        backButton.setContentAreaFilled(false);
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        getContentPane().add(backButton);
        backButton.setBounds(10, 460, 40, 40);

        homeButton.setContentAreaFilled(false);
        homeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeButtonActionPerformed(evt);
            }
        });
        getContentPane().add(homeButton);
        homeButton.setBounds(150, 460, 50, 40);

        forwardButton.setContentAreaFilled(false);
        getContentPane().add(forwardButton);
        forwardButton.setBounds(310, 460, 50, 40);

        menuBar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nciapp/menuBar.png"))); // NOI18N
        getContentPane().add(menuBar);
        menuBar.setBounds(0, 450, 360, 50);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nciapp/wallpaper3.png"))); // NOI18N
        getContentPane().add(background);
        background.setBounds(0, 0, 360, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents
//will add soon. 
    private void pastResultsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pastResultsButtonActionPerformed
        // TODO add your handling code here:
        //resultsLabel.setVisible(true);
    }//GEN-LAST:event_pastResultsButtonActionPerformed

    private void helpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpButtonActionPerformed
        // TODO add your handling code here:
        helpLabel.setVisible(true);
    }//GEN-LAST:event_helpButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
         GUIMathSupport myMaths = new GUIMathSupport();
         myMaths.setVisible(true);
         this.setVisible(false);
    }//GEN-LAST:event_backButtonActionPerformed

    private void homeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeButtonActionPerformed
        // TODO add your handling code here:
         GUIMainMenu myMenu = new GUIMainMenu();
         myMenu.setVisible(true);
         this.setVisible(false);
    }//GEN-LAST:event_homeButtonActionPerformed
//opens new window
    private void playQuizButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playQuizButtonActionPerformed
        // TODO add your handling code here:
        QuizApp myQuiz = new QuizApp ();
        myQuiz.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_playQuizButtonActionPerformed

    private void helpLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_helpLabelMouseClicked
        // TODO add your handling code here:
        helpLabel.setVisible(false);
    }//GEN-LAST:event_helpLabelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new GUIQuiz().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JLabel background;
    private javax.swing.JButton forwardButton;
    private javax.swing.JButton helpButton;
    private javax.swing.JLabel helpLabel;
    private javax.swing.JButton homeButton;
    private javax.swing.JLabel menuBar;
    private javax.swing.JButton pastResultsButton;
    private javax.swing.JButton playQuizButton;
    private javax.swing.JLabel titleText;
    // End of variables declaration//GEN-END:variables
}
