/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package nciapp;

/**
 * NCI App
 * Sean Keeley
 * Maths Support Section
 */
public class GUISupport extends javax.swing.JFrame {

    /**
     * Creates new form SupportGUI
     */
    public GUISupport() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backButton = new javax.swing.JButton();
        homeButton = new javax.swing.JButton();
        forwardButton = new javax.swing.JButton();
        noteButton = new javax.swing.JButton();
        notesLabel = new javax.swing.JLabel();
        infoLabel = new javax.swing.JLabel();
        titleText = new javax.swing.JLabel();
        menuBar = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(374, 535));
        getContentPane().setLayout(null);

        backButton.setContentAreaFilled(false);
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        getContentPane().add(backButton);
        backButton.setBounds(0, 460, 40, 40);

        homeButton.setContentAreaFilled(false);
        getContentPane().add(homeButton);
        homeButton.setBounds(160, 460, 40, 40);

        forwardButton.setContentAreaFilled(false);
        getContentPane().add(forwardButton);
        forwardButton.setBounds(320, 460, 40, 40);

        noteButton.setText("Take a note");
        noteButton.setOpaque(false);
        noteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noteButtonActionPerformed(evt);
            }
        });
        getContentPane().add(noteButton);
        noteButton.setBounds(120, 390, 110, 23);

        notesLabel.setFont(new java.awt.Font("Calibri", 0, 36)); // NOI18N
        notesLabel.setForeground(new java.awt.Color(240, 240, 240));
        notesLabel.setText("  Take a note!");
        getContentPane().add(notesLabel);
        notesLabel.setBounds(70, 330, 220, 40);

        infoLabel.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        infoLabel.setForeground(new java.awt.Color(255, 255, 255));
        infoLabel.setText("<html> The Mathematics Support Service is located on the ground floor beside Student Services. Run by Johnathan Lambert the service is open to all students in the college who may be struggling with Maths. Students in a business or computing are recommened to attend the service if they feel they are slipping behind. The centre is open normal office hours, Monday to Friday and is available for booked group sessions as well as drop-in session if available. The service is free of charge and is open to anyone who feels they may need that extra bit of help.\nAround exam time, the centre also runs exam revision driven sessions where they will tackle likely to come up exams topics. Be sure to check the noticeboard and your student email for further information. </html>");
        getContentPane().add(infoLabel);
        infoLabel.setBounds(10, 40, 340, 290);

        titleText.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        titleText.setForeground(new java.awt.Color(240, 240, 240));
        titleText.setText("Support");
        getContentPane().add(titleText);
        titleText.setBounds(260, 10, 130, 40);

        menuBar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nciapp/menuBar.png"))); // NOI18N
        getContentPane().add(menuBar);
        menuBar.setBounds(0, 450, 360, 50);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nciapp/wallpaper3.png"))); // NOI18N
        getContentPane().add(background);
        background.setBounds(0, 0, 360, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        GUIMathSupport myMaths = new GUIMathSupport();
        myMaths.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_backButtonActionPerformed

    private void noteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noteButtonActionPerformed
        // TODO add your handling code here:
        Notes myNotes = new Notes();
        myNotes.setVisible(true);
        this.setVisible(false);
        
        
    }//GEN-LAST:event_noteButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUISupport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUISupport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUISupport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUISupport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new GUISupport().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JLabel background;
    private javax.swing.JButton forwardButton;
    private javax.swing.JButton homeButton;
    private javax.swing.JLabel infoLabel;
    private javax.swing.JLabel menuBar;
    private javax.swing.JButton noteButton;
    private javax.swing.JLabel notesLabel;
    private javax.swing.JLabel titleText;
    // End of variables declaration//GEN-END:variables
}
