/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package nciapp;

import javax.swing.JOptionPane;

/**
 *
 * @author x12383876
 */
public class GUISWAT extends javax.swing.JFrame {

    /**
     * Creates new form Computing
     */
    public GUISWAT() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        moodleButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        mainText = new javax.swing.JLabel();
        SwatBanner = new javax.swing.JLabel();
        menuMiddle = new javax.swing.JButton();
        menuLeft = new javax.swing.JButton();
        menuRight = new javax.swing.JButton();
        MenuBar = new javax.swing.JLabel();
        Wallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(374, 535));
        setPreferredSize(new java.awt.Dimension(376, 539));
        getContentPane().setLayout(null);

        moodleButton.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        moodleButton.setText("To Moodle");
        moodleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moodleButtonActionPerformed(evt);
            }
        });
        getContentPane().add(moodleButton);
        moodleButton.setBounds(240, 340, 100, 50);

        jLabel1.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText(" Study, Workshop and Tutoring ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 60, 250, 40);

        mainText.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        mainText.setForeground(new java.awt.Color(255, 255, 255));
        mainText.setText("<html><br/> <br/>  SWAT: Referencing & Academic Writing <br/>   <br/>  SWAT: Touch Typing <br/>  <br/>  SWAT Training: Research <br/>   <br/>  SWAT Training: Problem Solving <br/>  <br/>  SWAT Training: Numeracy <br/>  <br/>  SWAT Training: Communication <br/> <br/> <br/> If you are not enrolled in the Computing Support please contact your teacher.   </html>");
        getContentPane().add(mainText);
        mainText.setBounds(20, 60, 220, 330);

        SwatBanner.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        SwatBanner.setForeground(new java.awt.Color(255, 255, 255));
        SwatBanner.setText("S.W.A.T.");
        getContentPane().add(SwatBanner);
        SwatBanner.setBounds(210, 10, 140, 30);

        menuMiddle.setContentAreaFilled(false);
        menuMiddle.setPreferredSize(new java.awt.Dimension(50, 50));
        menuMiddle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuMiddleActionPerformed(evt);
            }
        });
        getContentPane().add(menuMiddle);
        menuMiddle.setBounds(150, 450, 60, 50);

        menuLeft.setContentAreaFilled(false);
        menuLeft.setPreferredSize(new java.awt.Dimension(50, 50));
        menuLeft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuLeftActionPerformed(evt);
            }
        });
        getContentPane().add(menuLeft);
        menuLeft.setBounds(0, 450, 60, 50);

        menuRight.setContentAreaFilled(false);
        menuRight.setPreferredSize(new java.awt.Dimension(50, 50));
        menuRight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRightActionPerformed(evt);
            }
        });
        getContentPane().add(menuRight);
        menuRight.setBounds(310, 450, 50, 50);

        MenuBar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nciapp/menuBar2.gif"))); // NOI18N
        MenuBar.setText("jLabel1");
        MenuBar.setPreferredSize(new java.awt.Dimension(360, 50));
        getContentPane().add(MenuBar);
        MenuBar.setBounds(0, 450, 360, 50);

        Wallpaper.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        Wallpaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nciapp/wallpaper3.png"))); // NOI18N
        Wallpaper.setMaximumSize(new java.awt.Dimension(412, 500));
        getContentPane().add(Wallpaper);
        Wallpaper.setBounds(0, 0, 360, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuLeftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuLeftActionPerformed
        // TODO add your handling code here:
        GUIComputingSupport myComputing = new GUIComputingSupport();
        myComputing.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_menuLeftActionPerformed

 

    private void menuMiddleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuMiddleActionPerformed
 GUIMainMenu myMainMenu = new GUIMainMenu();
        myMainMenu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_menuMiddleActionPerformed

    private void moodleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moodleButtonActionPerformed
        // TODO add your handling code here:
        try {
        String URL ="https://moodle.ncirl.ie/course/view.php?id=1199";
        java.awt.Desktop.getDesktop().browse(java.net.URI.create(URL));
    }
            catch (Exception e) {
                JOptionPane.showMessageDialog(null,e.getMessage());
            }
    }//GEN-LAST:event_moodleButtonActionPerformed

    private void menuRightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRightActionPerformed
        // TODO add your handling code here:
        ArrayGUI myArrayGUI = new ArrayGUI();
        myArrayGUI.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_menuRightActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUISWAT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUISWAT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUISWAT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUISWAT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new GUISWAT().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel MenuBar;
    private javax.swing.JLabel SwatBanner;
    private javax.swing.JLabel Wallpaper;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel mainText;
    private javax.swing.JButton menuLeft;
    private javax.swing.JButton menuMiddle;
    private javax.swing.JButton menuRight;
    private javax.swing.JButton moodleButton;
    // End of variables declaration//GEN-END:variables
}
