/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package nciapp;

/**
 * NCI App
 * Sean Keeley
 * Maths Support Section 
 * 
 * I can't get this quiz to work the way that i wanted and  
 * I took 
 */
public class QuizApp extends javax.swing.JFrame {

    /**
     * Creates new form QuizApp
     */
    public QuizApp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        checkButton = new javax.swing.JButton();
        resetButton = new javax.swing.JButton();
        answerLabel = new javax.swing.JLabel();
        answerTf = new javax.swing.JTextField();
        questionLabel = new javax.swing.JLabel();
        questionTf = new javax.swing.JTextField();
        titleLabel = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();
        homeButton = new javax.swing.JButton();
        menuBar = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(374, 535));
        setPreferredSize(new java.awt.Dimension(374, 535));
        getContentPane().setLayout(null);

        checkButton.setText("Check Answer");
        checkButton.setOpaque(false);
        getContentPane().add(checkButton);
        checkButton.setBounds(20, 380, 110, 50);

        resetButton.setText("Reset Quiz");
        resetButton.setOpaque(false);
        getContentPane().add(resetButton);
        resetButton.setBounds(245, 380, 100, 50);

        answerLabel.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        answerLabel.setForeground(new java.awt.Color(240, 240, 240));
        answerLabel.setText("Answer:");
        getContentPane().add(answerLabel);
        answerLabel.setBounds(100, 280, 80, 30);

        answerTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answerTfActionPerformed(evt);
            }
        });
        getContentPane().add(answerTf);
        answerTf.setBounds(80, 310, 180, 50);

        questionLabel.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        questionLabel.setForeground(new java.awt.Color(240, 240, 240));
        questionLabel.setText("Question:");
        getContentPane().add(questionLabel);
        questionLabel.setBounds(60, 100, 100, 30);

        questionTf.setEditable(false);
        questionTf.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        questionTf.setForeground(new java.awt.Color(240, 240, 240));
        questionTf.setOpaque(false);
        getContentPane().add(questionTf);
        questionTf.setBounds(40, 130, 270, 120);

        titleLabel.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(240, 240, 240));
        titleLabel.setText("Try our Quiz");
        getContentPane().add(titleLabel);
        titleLabel.setBounds(230, 0, 240, 60);

        backButton.setContentAreaFilled(false);
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        getContentPane().add(backButton);
        backButton.setBounds(0, 460, 60, 40);

        homeButton.setContentAreaFilled(false);
        homeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeButtonActionPerformed(evt);
            }
        });
        getContentPane().add(homeButton);
        homeButton.setBounds(150, 463, 50, 40);

        menuBar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nciapp/menuBar.png"))); // NOI18N
        getContentPane().add(menuBar);
        menuBar.setBounds(0, 450, 360, 50);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nciapp/wallpaper3.png"))); // NOI18N
        getContentPane().add(background);
        background.setBounds(0, 0, 360, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        GUIQuiz myQuiz = new GUIQuiz ();
        myQuiz.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_backButtonActionPerformed

    private void homeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeButtonActionPerformed
        // TODO add your handling code here:
        GUIMainMenu myMenu = new GUIMainMenu ();
        myMenu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_homeButtonActionPerformed

    private void answerTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answerTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_answerTfActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuizApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuizApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuizApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuizApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            
            @Override
            public void run() {
                new QuizApp().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel answerLabel;
    private javax.swing.JTextField answerTf;
    private javax.swing.JButton backButton;
    private javax.swing.JLabel background;
    private javax.swing.JButton checkButton;
    private javax.swing.JButton homeButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel menuBar;
    private javax.swing.JLabel questionLabel;
    private javax.swing.JTextField questionTf;
    private javax.swing.JButton resetButton;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
